# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/Users/juergenkober/Projects/Rust/_github-repos/miscellaneous-rust-code-alongs/building-web-apis-with-rust/rocket-app-beginners/migrations"
